### ISSUE TITLE
Issue with the body friction and bodies going to sleep

### ISSUE THREAD

**Issue by PanAMD** [erayzesen/QuarkPhysics#4] opened 2024-08-05 02:31 UTC
These two issues might as well be related, I modified the code in order to avoid the bodies falling asleep when they are still in use:
![image](https://github.com/user-attachments/assets/58577ad6-06ed-469f-9558-3683dbc09759)
Anyway that is not the complete problem, it seems like when bodies have the friction field is different than 0 and the body hasn't been in use, the friction (or something else) gets incremented and when trying to move the body once again (by using ApplyForce or ApplyImpulse) the body barely moves.
![2024-08-0420-01-54-ezgif com-video-to-gif-converter](https://github.com/user-attachments/assets/25b49c02-220e-45b2-95ea-c349c65e8ea8)

**Comment by erayzesen** [comment] 2024-08-17 13:36
Hi @PanAMD. Can you share some information about bodies in contact? 

Body type, mode, kinematic... All your specified body settings. Or code blocks about these bodies.

Provide me with data to reproduce the error.

**Comment by PanAMD** [comment] 2024-08-18 08:21
Hi @erayzesen thank you so much for your response, however it seems like the problem was with the world's SetSleepingEnabled not set to false. I do however have another problem related to the QRigidBody's speed when the body is falling and we try to move in the x axis, it seems like when the body is falling (due to the world's gravity) the body falls normally but if while the body is falling you try to move in the x axis the velocity in the x axis get's increased dramatically, here is an example: 
![2024-08-1802-00-20-ezgif com-crop](https://github.com/user-attachments/assets/b6b7d923-e261-4812-a972-f4564b8eef13)
Here are the body settings:
Mode: Dynamic
Friction: 2
Restitution: 0
FixedRotation: true

Here is my logic to move the player around:
`void PlayerSystem::update(const float & dt)
{
    for (auto & it : *(*getEntities()).getEntities())
    {
        auto& body(it.getComponent<PhysicsComponent>());
        auto& sprite(it.getComponent<SpriteComponent>());
        auto& keys(it.getComponent<PlayerComponent>());

        body.body->CollisionEventListener = std::bind(&PlayerSystem::onCollision, this, placeholders::_1, placeholders::_2);

        QVector velocity;

        float moveAccelerationRate=0.4f;
        float moveDecelarationRate=0.3f;
        float moveMaxSpeed=4.3f;

        int moveAxis = ((keys.isRightPressed )-(keys.isLeftPressed) );

        if(moveAxis == 0)
        {
            // If doesn't exist the input
            velocity.x += -velocity.x*moveDecelarationRate;
        }
        else
        {
            //Adding horizontal velocity
            velocity.x += ((moveMaxSpeed*moveAxis)-velocity.x)*moveAccelerationRate;
        }

        if(keys.isJumping and keys.isGrounded)
        {
            velocity.y = -20;
            keys.isGrounded = false;
        }
        body.body->ApplyImpulse(velocity, body.body->GetPosition());
    }
}`

Let me know if you need more information

**Comment by erayzesen** [comment] 2024-08-18 16:11
Thank you @PanAMD 

First of all, let me address the problem you are currently experiencing.

If you are working on a platformer character, it would make more sense to make the body kinematic. In fact, we even have a platformer example in our repo specifically for this purpose. Kinematic objects are those that can collide with other objects, but their position, velocity, and acceleration are controlled by you. 

The issue you're facing here is not a bug; you would get the same result in any physics engine. If you apply impulse or force to an object in the simulation every frame, the object's acceleration will increase exponentially, causing it to speed up significantly. By doing this, you are essentially increasing the object's acceleration each frame. 

If you want to create a character without the kinematic feature, which you might need, that's also possible. We have a great feature for this as well—rather than applying impulse or force to the object, directly change its position. You can safely change the position of objects using the [QRigidBody::SetPositionAndCollide(QVector value, bool withPreviousPosition)](https://erayzesen.github.io/QuarkPhysics/documentation/classQRigidBody.html#a5613b4dbd8f51b37a4c3e940f065710a) method. If you set the withPreviousPosition parameter to true, the acceleration will reset, and the object will only move to that position. If set to false, the new position will be applied, but the new acceleration will be calculated based on the previous position. If you want a non-kinematic object with more control, we have a fantastic virtual function called [QBody::OnPreStep()](https://erayzesen.github.io/QuarkPhysics/documentation/classQBody.html#a00f0e011bd36088c6619bf7b11bf2ff5). Here, you can manipulate your object before it enters the simulation at each step, and then it will enter the simulation. In a way, you write your own behavior and even constraints for the object before it is introduced to the simulation, and then the simulation processes it in the physics step to produce a result.

I would love to reproduce the issue you're experiencing with the sleep feature. From what I understand, you are applying an impulse or force to an object with the CanSleep feature enabled after it has entered sleep mode, and it’s not moving. If you could provide more details about this problem, it would be very helpful for us. This way, we can resolve the issue as well.

**Comment by erayzesen** [comment] 2024-09-12 03:05
I am closing this issue for now as information exchange could not be continued.

**Closed as completed by erayzesen** 2024-09-12 03:05 UTC
